### ISSUE TITLE
Answer all option/Save selected answers

### ISSUE THREAD

**Issue by tobias-haenel** [mheider/amcs_issues#1]
I tried to answer all questions at once and did not press the answer button ("Beantworten"). After submitting one answer, my other selections were removed. Maybe there should be a option to answer all questions at once or selections should be saved. Another option i could think of: Only present one question at a time and have next/back/skip buttons.

**Comment by kubica** [comment]
works now. selected answers does not reset. the "one question at a time"-idea gets noted in our private issue tracker (ty for this idea :+1: )
