### ISSUE TITLE
Einzelauswertung einer Frage wird nicht geupdatet

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#10]
Wenn ich in der Auswertung die Frageliste anschaue, wird diese regelmaessig mit neuen Studentenantworten geupdatet. Wenn ich allerdings eine einzelne Frage anklicke, um diese in der Grossansicht zu sehen, wird diese nicht mehr geupdatet, sondern ich muss erst wieder zurueck zur Uebersicht, um Updates zu bekommen.

Dies ist insbesondere fuer StudyQuestions unpraktisch, da man in der Uebersicht die Antwortvorgaben nicht angezeigt bekommt.

**Comment by kubica** [comment]
Ich werde versuchen dafür bis nächste Woche eine Lösung zu finden. Wird jedoch komplexer als es aussieht aber wird als nächstes in Angriff genommen.

**Comment by kubica** [comment]
Sollte soweit funktionieren für alle Fragetypen und sowohl für Slide/als auch Lecture Questions.
Die Aktualisierung erfolgt ähnlich wie in der Übersicht nach einigen Sekunden.

Ich teste später nochmal genauer ob wirklich jeder Fall abgedeckt ist und keine Probleme auftreten. Gerade lief aber alles prima :+1:

**Comment by fsiegert** [comment]
Super, scheint zu funktionieren, und werde ich morgen in der Vorlesung gleich ausprobieren. Danke!
