### ISSUE TITLE
"Veranstaltung editieren" funktioniert nicht

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#11]
Wenn man die Veranstaltungsdetails (z.B. Datum/Zeit) bearbeiten moechte, kann man das ja in den Dialogfeldern tun, allerdings geschieht beim Klick auf das finale "Veranstaltung editieren" nichts.

**Comment by kubica** [comment]
`TypeError: Cannot read property 'getFullYear' of undefined` - wird so schnell wie möglich behoben

**Comment by kubica** [comment]
fixed

**Comment by fsiegert** [comment]
Thanks, it works now.
