### ISSUE TITLE
Balkendiagramme fuer Multiple-Choice-Fragen

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#12]
Fuer Multiple-Choice-Fragen waere es sinnvoll, die Antworten in einem Balkendiagramm darzustellen, statt in einer Torte.

**Comment by kubica** [comment]
Die Umsetzung wie bei den ScaleQuestions (Antworten an der x-Achse) war nicht möglich, da die Antwort-Texte bei MultipleChoiceQuestions im Gegensatz zu ScaleQuestions sehr lang sein können (das sah dann in etwa so aus).
<img width="414" alt="bildschirmfoto 2015-10-31 um 07 01 04" src="https://cloud.githubusercontent.com/assets/4146400/10862415/0e1a59f2-7fa7-11e5-895c-9d996990b832.png">

Daher habe ich es jetzt analog zu den SingleChoiceQuestions gelöst (Antworten werden verkürzt darunter angezeigt):
<img width="408" alt="bildschirmfoto 2015-10-31 um 08 05 02" src="https://cloud.githubusercontent.com/assets/4146400/10862411/cf5482d8-7fa6-11e5-92af-76b527f9f9a3.png">

In der Modalansicht das selbe Problem, wodurch ich es auch dort ähnlich wie bei den SingleChoiceQuestions gelöst habe:
<img width="1120" alt="bildschirmfoto 2015-10-31 um 08 04 47" src="https://cloud.githubusercontent.com/assets/4146400/10862425/360448e2-7fa7-11e5-8f96-51cfccab8b09.png">

Ich werde nurnoch einige Tests durchführen und das Ganze dann umgehend commiten :)

**Comment by fsiegert** [comment]
Sieht sehr gut aus, danke!
