### ISSUE TITLE
Randomisierte Verteilung der StudyQuestion Antworten in Auswertung ohne Loesung

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#13]
In der Grossansicht bei der Auswertung von StudyQuestion's werden ja in der Legende die Antwortmoeglichkeiten erst ohne Farbe angezeigt, damit diese den gegebenen Antwort-Verhaeltnissen nicht zuzuordnen sind.

Das funktioniert nicht wirklich, weil die Reihenfolge der Antworten direkt im Uhrzeigersinn des Tortendiagramms in der Legende stehen, man diese also auch ohne Farben schon zuordnen kann, wenn man das einmal verstanden hat.

**Comment by fsiegert** [comment]
Sorry, zu zeitig abgeschickt: Vorschlag waere natuerlich, die Reihenfolge in der Legende zu randomisieren.

**Comment by kubica** [comment]
Anstatt die Reihenfolge in der Legende zu randomisieren werde ich versuchen die Reihenfolge im Diagramm direkt zu ändern, da viele Studenten sich die Nummer ihrer Antworten merken. Problem dabei ist dann wieder, dass Antwort 1 in der Legende immer die Farbe "blau" hat, wodurch ich die Farben an sich auch noch randomisieren werde :+1:

**Comment by kubica** [comment]
Sollte jetzt alles funktionieren und randomisiert sein, wie ich es oben vorgeschlagen hatte.

<img width="888" alt="bildschirmfoto 2015-10-31 um 10 00 44" src="https://cloud.githubusercontent.com/assets/4146400/10862782/59713d8e-7fb7-11e5-82a0-7971e8c94f62.png">

vs.

<img width="896" alt="bildschirmfoto 2015-10-31 um 10 00 34" src="https://cloud.githubusercontent.com/assets/4146400/10862789/7c2edc64-7fb7-11e5-8ba0-c30822e7b1f7.png">

**Comment by fsiegert** [comment]
Cool, sieht gut aus. Danke!
