### ISSUE TITLE
App gibt falsches Feedback in StudyQuestions

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#14]
Mir haben mehrere Studenten gemeldet, dass die App ihnen falsches Feedback fuer StudyQuestions gegeben hat. Sie haben beispielsweise die richtige Antwort ausgewaehlt, aber die App hat ihnen das Feedback einer falschen Antwort gegeben.

Soweit ich richtig verstehe, ist allerdings in der Auswertung die richtige Antwort gezaehlt worden -- die Studenten koennen es zwar nicht sehen, aber berichteten von Feedback einer (falschen) Antwort die in der Auswertung keine einzige Stimme bekommen hatte.

Ich kann es auf Anhieb nicht reproduzieren, vielleicht taucht das Problem aber auch nicht immer auf?

**Comment by fsiegert** [comment]
PS: Das betrifft explizit nur die App, und der workaround besteht natuerlich, auf dem Handy einfach das Web-Interface zu verwenden.

**Comment by PatrickBTUD** [comment]
Problem gefunden und gelöst.
Die neue Version sollte von Google in ein paar Stunden freigegeben werden, dann kann die App aktualisiert werden.

**Comment by fsiegert** [comment]
Ich habe die neue Version gerade probiert, und das Problem taucht bei mir nicht auf. Mal schauen, ob die Studenten morgen immer noch davon berichten.
Ein Problem gibt es bei der neuen App allerdings: Man kann mit der App eine Frage scheinbar beliebig oft beantworten (durch erneutes Laden der Vorlesung). Aber dafuer oeffne ich ein separates Ticket.
