### ISSUE TITLE
App erlaubt mehrfache Beantwortung der gleichen Frage

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#15]
Man kann mit der App seit dem heutigen(?) Update eine Frage scheinbar beliebig oft beantworten (durch erneutes Laden der Vorlesung). Im Webinterface wird korrekterweise angezeigt "Sie haben alle Fragen auf dieser Folie bereits beantwortet." aber die App laesst mich immer wieder antworten.

**Comment by PatrickBTUD** [comment]
Das sollte eigentlich nur bei den Lernfragen auftreten, wenn die Frage beim ersten Mal richtig beantwortet wurde und beim neuladen der Vorlesung wird die Frage wieder angezeigt. Dann hat man wieder die Möglichkeit zwei mal zu antworten, aber spätestens dann sollte die Frage nicht mehr angezeigt werden.
Trotzdem ist das falsch und wird demnächst behoben.
