### ISSUE TITLE
Kursfragen: Antworten zuruecksetzen

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#16]
Das "Antworten zuruecksetzen" schliesst momentan Kursfragen nicht ein, und ich sehe keine Moeglichkeit, die Antworten fuer diese zurueckzusetzen.

**Comment by knobsam** [comment]
Hi, im Kontext "Veranstaltung" ist das ein normales Verhalten, denn da werden nur die Antworten der Veranstaltungs- und Folienfragen resettet. Kursfragen sind dem übergeordnet, die werden normal ja nur einmalig pro Semester/Kursdauer beantwortet.
Davon abgesehen, die Möglichkeit für einen Reset der Antworten bei Kursfragen werden wir mit implementieren und bereitstellen.

VG

**Comment by kubica** [comment]
Vielen Dank für den Hinweis, dass diese Funktionalität noch gefehlt hat.

Es ist jetzt in der **Fragenübersicht** möglich, die Antworten einzelner Fragen zu resetten.
<img width="899" alt="bildschirmfoto 2016-10-17 um 14 40 01" src="https://cloud.githubusercontent.com/assets/4146400/19439925/35cce6a6-9480-11e6-9345-9b8a3486999f.png">

Ebenso ist es unter **Antworten zurücksetzen** möglich, die Antworten der aktuellen Lehrveranstaltung (Folien-/Veranstaltungsfragen) oder die Antworten der Kursfragen zurückzusetzen.
<img width="963" alt="bildschirmfoto 2016-10-17 um 15 32 01" src="https://cloud.githubusercontent.com/assets/4146400/19439987/6f07864c-9480-11e6-9c03-281338109948.png">

Im Zweifel mit der Maus über die Buttons fahren, um mehr Informationen dazu zu bekommen.
<img width="331" alt="bildschirmfoto 2016-10-17 um 15 45 55" src="https://cloud.githubusercontent.com/assets/4146400/19440084/d46e2478-9480-11e6-8980-e2877478d231.png">

**Comment by fsiegert** [comment]
Perfekt, vielen Dank fuer die schnelle Reaktion!
