### ISSUE TITLE
lecture overview should be sorted by date

### ISSUE THREAD

**Issue by mattisebastian** [mheider/amcs_issues#17]
In the lecture overview (/courses) there should be a sorting option or just sort the lectures by date.

**Comment by knobsam** [comment]
Thanks, we'll add a sort option soon.

**Comment by knobsam** [comment]
Got some questions: 
Our frontend developer said, the route "/courses" was removed several weeks ago. The only lists you should see as a "student" user are the list of lectures active (left, sorted by date) and the courses you are enrolled into (right). As "lecturer" you should see your active lecture and the ones you have enrolled into, on the right side your courses and the ones you have enrolled into. Both lists should be short and overseeable.

Could you specify your problem, please?

**Comment by kubica** [comment]
Hey @mattisebastian , thanks for your suggestion.
What you mean is the page i screenshoted for an example below, right?

<img width="879" alt="bildschirmfoto 2016-10-26 um 13 51 29" src="https://cloud.githubusercontent.com/assets/4146400/19724994/687a3e32-9b83-11e6-9f40-536765999ea7.png">

At the moment the lectures are **already sorted first by their "on_air" state and second by "date"**.
In the example the dates are not set correctly for all lectures yet. Thats why the sorting is confusing.

Can you provide any further informations for your problem? (name of the course, what sorting informations should be provided (possibility for a custom sorting?)).
Would it help for you to add a search field to the page?

Thanks!

**Comment by mattisebastian** [comment]
Hey,

I was referring to this lecture:
![image](https://cloud.githubusercontent.com/assets/2878488/19757830/69285312-9c25-11e6-9ad0-2f3b3826792a.png)

From my point of view no search field is necessary if the content is tagged correctly. I would just need the lectures in the correct order in which they are held.

Best regards
Matti

**Comment by kubica** [comment]
FInally done
![bildschirmfoto 2017-11-02 um 15 03 31](https://user-images.githubusercontent.com/4146400/32330025-1791831e-bfdf-11e7-92f2-c0588ae75259.png)
