### ISSUE TITLE
Nach Exportieren eines Kurses sind Fragen gleichzeitig Folien- und Veranstaltungsfragen

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#18]
Seit mindestens gestern scheint es einen Bug zu geben: Wenn ich eine Veranstaltung aktiv schalte, koennen die Studenten _alle_ Fragen der Veranstaltung sehen, nicht nur die auf der aktuellen Folie.

**Comment by knobsam** [comment]
Hi, kannst du bitte mal den Namen des Kurses und der Veranstaltung nennen, damit ich das überprüfen kann?

**Comment by fsiegert** [comment]
Das passiert bei mir im Kurs "Teilchen- und Kernphysik WS 2016/17" z. B. in der gerade aktiven Veranstaltung "Die Dirac-Gleichung".

**Comment by knobsam** [comment]
Danke, habe es mir angesehen. Das Problem ist, dass die Fragen sowohl als Veranstaltungs- als auch Folienfragen angelegt wurde (das sollte "eigentlich" nicht möglich sein). Heißt, die Fragen werden generell als Veranstaltungsfragen angezeigt und (doppelt) noch einmal auf der entsprechenden Folie.

Wurden die Fragen über das Web-Interface angelegt oder via PowerPoint?

Wir werden das noch mal prüfen, wo der Fehler herkommt.

**Comment by fsiegert** [comment]
Oha, vielen Dank fuer den Hinweis, jetzt sehe ich das auch! Ich habe die Fragen ueber das Web-Interface angelegt. Soweit ich mich erinnere, habe ich die von der alten Vorlesung (2015) kopierten Fragen mit Hilfe der Template-Funktion nochmal hinzugefuegt, um die Reihenfolge anzupassen. Vielleicht ist mir dabei ein Fehler unterlaufen? Ich werde das in Zukunft beobachten und ggf. nochmal hier schreiben, falls es nochmal passiert.

**Comment by fsiegert** [comment]
Ich sehe gerade, dass es bei anderen Veranstaltungen im gleichen (aus 2015 geklonten) Kurs das gleiche Problem gibt, obwohl ich dort noch nichts manuell veraendert habe. Zum Beispiel in der Veranstaltung "Wechselwirkungen". Es scheint also, als ob das Problem beim Klonen entstanden ist, kann das sein?

Wie kann ich jetzt (idealerweise bis morgen) das doppelte/vorzeitige Auftreten der Fragen zumindest in der Veranstaltung "Die Dirac-Gleichung" verhindern? Manuell kann ich sie ja nur komplett oder gar nicht loeschen, oder?

**Comment by knobsam** [comment]
Ok, dann wird es vermutlich an der Klon-Routine liegen.

Für deine morgige Vorlesung kann ich das Problem aktuell nur manuell lösen, indem ich die falsch gesetzte ID der Vorlesung händisch entferne.
Werde ich dann direkt machen.

**Comment by fsiegert** [comment]
Super, danke!

**Comment by knobsam** [comment]
Ist korrigiert.
Das Problem selbst schauen wir und auf jeden Fall noch an, warum es aufgetreten ist.

**Comment by knobsam** [comment]
Problem ist behoben und wird heute Abend auf den Server aufgespielt.
Wenn möglich, bitte bis dahin keinen Export (das Wolkensymbol) durchführen, der erzeugt den Fehler mit der doppelten Zuweisung von Fragen.

**Comment by fsiegert** [comment]
Danke fuer's Nachforschen und Beheben!
