### ISSUE TITLE
Antwortvorgaben drehen sich beim Submitten plötzlich um

### ISSUE THREAD

**Issue by majewsky** [mheider/amcs_issues#5]
Gesehen in Rechnernetze, Vorlesung "Mobile Computing", Folie 33. Bei der ersten Frage hatte ich den Regler auf "Trifft gar nicht zu" geschoben, nach dem Submit steht dort aber plötzlich "Trifft völlig zu". Es kommt ein starkes Gefühl auf von "Traue keiner Statistik, die du nicht selbst gefälscht hast".

![amcs-bug](https://cloud.githubusercontent.com/assets/24696/8720628/281c8600-2bb4-11e5-9c52-a93cafcb38a0.png)

**Comment by kubica** [comment]
fixed
