### ISSUE TITLE
On/Off switch for lecture does not change state when switching to On

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#8]
Title says it all, the On/Off switch does not change its visible state when switching it to "On". On the other hand, when switching to "Off" the state changes.

**Comment by mheider** [comment]
Issue fixed in latest release.

**Comment by kubica** [comment]
Das active_slide_set wird beim Wechsel auf on_air teilweise null, wodurch nach dem Refresh der Seite die Slides verschwinden. Workaround genau wie zuvor: nochmal auf off_air setzen und wieder auf on_air, danach Seite neu laden.
