### ISSUE TITLE
Antworten von StudyQuestions werden in der Auswertung nicht angezeigt

### ISSUE THREAD

**Issue by fsiegert** [mheider/amcs_issues#9]
Wenn ich in der Auswertung auf eine StudyQuestion clicke, um sie gross zu machen, dann werden die moeglichen Antworten nicht immer als Legende angezeigt, d.h. das Tortendiagramm ist unbeschriftet. Zum Beispiel habe ich eine mit 5 Optionen, die alle angezeigt werden, waehrend eine andere Frage nur 3 Optionen hat, und dort werden die Beschriftungen nicht angezeigt (siehe Test2-Veranstaltung in der T+K-Physik).

**Comment by kubica** [comment]
Besteht das Problem nach wie vor an irgendeiner Stelle?

**Comment by fsiegert** [comment]
Ich kann es gerade nicht mehr reproduzieren, und da die Beschriftung des Tortendiagramms jetzt sowieso viel cleverer ist, schliesse ich dieses Ticket erstmal. Danke fuer die Updates!

**Comment by kubica** [comment]
Sehr gut! Sobald Sie ansonsten Fehler finden oder auch Verbesserungsvorschläge haben immer fleißig weiter eintragen. Das hilft uns sehr gut weiter :+1:
